language: node_js
node_js: "14"
cache: yarn
os: linux
dist: bionic

addons:
  chrome: "stable"
  firefox: "latest"

notifications:
  email:
    - vieira.joaopaulo.91@gmail.com

before_script: "yarn lint"
